### ISSUE TITLE
root schema import

### ISSUE THREAD

**Issue by zhenyulin** [prisma/graphql-import#221]
I'm currently working on separate different type definitions into different .graphql files with graphql-import, and was wondering if it is possible to do some wild card import to stitch all types into an index.graphql file to be imported as typeDefs?

examples:

item.graphql
```js
type Item {
	id: ID!
	name: String
}

type Query {
	Items: [Item]
	Item(id: ID!): Item
}
```
user.graphql
```js
# import Item from "item.graphql"

type User {
	id: ID!
	name: String
	email: String!
	follows: [User] @relation(name: "FOLLOWS", direction: "OUT")
	followers: [User] @relation(name: "FOLLOWS", direction: "IN")
	likes: [Item] @relation(name: "LIKES", direction: "OUT")
}

type Query {
	Users: [User]
	User(id: ID!, name: String, email: String): User
	UserByLikedItem(itemId: ID!): [User] @cypher(statement: "MATCH (i:Item) <- [r:LIKES] - (u:User) RETURN u")
}
```

index.graphql
```js
# import * from "item.graphql"
# import * from "user.graphql"
```

**Comment by SpaceK33z** [comment]
To import everything, the query + mutation schemes + other types, you can use this:

```graphql
import Query.*, Mutation.*, * from "item.graphql"
```

I'll leave this open because the documentation isn't clear about this (the behavior changed in v0.6.0).

**Comment by SpaceK33z** [comment]
Documented on https://oss.prisma.io/content/graphql-import/overview now.
