### ISSUE TITLE
Consider package imports.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [prisma/graphql-import#57]
Consider the example from `graphql-binding-github`.
```
# import Repository from "./github.graphql"

type Query {
  hello(name: String): String!
  favoriteRepos: [Repository!]!
}
```
It requires an up to date `github.graphql`, which is generated, to exist next to `app.graphql`, which is not.  `github.graphql` also has to be put into version control and manually regenerated whenever the GitHub GraphQL endpoint is updated.
However, `graphql-binding-github` exports a `github.graphql`.  Using that, I wouldn't have to put it in version control or regenerate it, just update `graphql-binding-github`.  But, rewriting it that way comes with another problem.
```
# import Repository from "../node_modules/graphql-binding-github/schema/schema.graphql"
```
Things get even hairier if `app.graphql` is deeply nested or in a monorepo.
Ideally, I should be able to do something like
```
# import Repository from "graphql-binding-github/schema/schema.graphql"
```
To take it a step further, you could default to a top-level `schema.graphql` or use a `graphql:main` field in the `package.json` and do something like
```
# import Repository from "graphql-binding-github"
```
I believe this is currently possible with Object Imports, but you'd have to do something like
```
const githubSchema = fs.readSync('Path to schema.graphql');
importSchema(mySchema, {'graphql-binding-github': githubSchema});
```

**Comment by schickling** [comment]
I remember @kbrandwijk working on something very similar?

**Comment by lfades** [comment]
Oh I just saw this issue it's related to this [PR](https://github.com/graphcool/graphql-import/pull/136), but it's never too late to comment!
